### ISSUE TITLE
[KE] Implement Sorookin's Relation Extractor

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/sask#1]
I as a user, want to be able to run my unstructured data against the webservice of https://iswc2017.ai.wu.ac.at/wp-content/uploads/2017/10/84.pdf

Bonus: Use the related work to find more Relation Extractors

**Comment by RicardoUsbeck** [comment]
Link not working

**Comment by RicardoUsbeck** [comment]
http://aclweb.org/anthology/D17-1188

**Comment by RicardoUsbeck** [comment]
http://semanticparsing.ukp.informatik.tu-darmstadt.de:5000/relation-extraction/static/index.html

**Comment by RicardoUsbeck** [comment]
Who is doing that? @sepidetari @Suganya31 @AndreSonntag @KHaack ?

**Comment by KHaack** [comment]
Currently not defined. Will we discuss Monday.

**Comment by KHaack** [comment]
merged in 995e041a4f3db03b17158d45edebf0c20d5c6314

**Comment by Suganya31** [comment]
@RicardoUsbeck Hi Ricardo, I wanted to inform you that the Sorookin link (http://semanticparsing.ukp.informatik.tu-darmstadt.de:5000/relation-extraction/) is not working anymore.

**Comment by RicardoUsbeck** [comment]
Please write an email to sorokin@ukp.informatik.tu-darmstadt.de

**Comment by Suganya31** [comment]
Sorokin link works now.
