### ISSUE TITLE
Chatbot cannot cope with "hi" or misspelled answers

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/sask#11]
![image](https://user-images.githubusercontent.com/4354740/34041463-61c293ee-e198-11e7-91f9-095f7e524108.png)

**Comment by prasanthhs** [comment]
@RicardoUsbeck  Spelling correction will be considered as a separate feature. 

The other case is a bug in rive script. @Juzerhk Please look into the same.

**Comment by Juzerhk** [comment]
Changes have been made in the existing code and the code is now able to handle this issue.

**Comment by prasanthhs** [comment]
Reopened for wait till merge to master branch.

**Comment by Juzerhk** [comment]
<img width="823" alt="chatbot_screenshot" src="https://user-images.githubusercontent.com/33219637/34081394-3a7524c2-e34c-11e7-9d05-7461b2e0798b.png">


The bug is fixed now and the chat is able to answer to "Hi" and "Hello" queries

**Comment by Juzerhk** [comment]
commit id : dca19479387535bbf609a9b03070cc274c0aec73. 
please check

**Comment by RicardoUsbeck** [comment]
will be checked via pull request

**Comment by RicardoUsbeck** [comment]
but the rivescript looks good, feel free to close after pull request
