### ISSUE TITLE
Deleted too many files?

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/sask#23]
This commit https://github.com/dice-group/sask/commit/8063b6d1d04a9a8d6a48c1d71ffa8d6499622f07 seems to delete every other microservice. What is going on here? If I merge this, at least 3 microservices will be gone.

**Comment by KHaack** [comment]
We already discussed this at the last Monday meeting. I manually merged the branch into mine. See 06564de45798b563743766ed570f1a3804629242
That branch should not be meged.

**Comment by Suganya31** [comment]
Hi Ricardo,
I am sorry It was my mistake while pushing the files. I dint pull the files from Master.  Kevin already manually merged the Open IE to the ui-workspace-repo .

**Comment by RicardoUsbeck** [comment]
Makes sense. How about deleting that branch and pull request then? But please fix the errors anyway.

**Comment by Suganya31** [comment]
We deleted the branch. We manually merged the branch, see 06564de.
