### ISSUE TITLE
Commons library

### ISSUE THREAD

**Issue by KHaack** [dice-group/sask#34]
We would like to introduce a commons library. For this purpose we would create the maven module `` commons``. It provides interfaces and common classes for all modules. For example, the Discoverer class, which is still in Webclient, but should also be known in other Microservices.

The problem here is that this module is not a sping boot application, but the depenencies/build from the parent pom make it one. Do you also see that we have to move the spring boot dependencies/build to the child modules? 
Or is there another good proposal?

**Comment by KHaack** [comment]
I talked to Ricardo about it today.
Ricardo does not want a (pseudo) console application, so we should prefer a real library.

**Comment by RicardoUsbeck** [comment]
=> move it to separate git repo

**Comment by KHaack** [comment]
ok
