### ISSUE TITLE
Javascript load issue rendering the UI non responsive to inputs

### ISSUE THREAD

**Issue by guru5590** [dice-group/sask#36]
Due to javascript issue the UI is rendered the UI not accepting inputs from the User.

Error : Failed to load resource jquery-ui.css : the server responded with a status of 404 (). 

Attached is the screenshot
<img width="1680" alt="screen shot 2018-04-23 at 17 20 03" src="https://user-images.githubusercontent.com/7804859/39136228-08be24b4-471b-11e8-8337-93f4c9e29982.png">

**Comment by KHaack** [comment]
Indirectly fixed in #35

**Comment by guru5590** [comment]
Even though the issue is fixed as part of the commit https://github.com/dice-group/sask/pull/35, Keeping this issue active, until the pull request is merged into the master branch

**Comment by guru5590** [comment]
Closing the issue, as pull request is merged into master branch
