### ISSUE TITLE
HAWK Guide 

### ISSUE THREAD

**Issue by KHaack** [dice-group/sask#63]
Currently i have no idea how to setup hawk. The guide on https://github.com/dice-group/NLIWOD/tree/master/qa.hawk doesnt work under Linux (DockerHub). Probably the build is corrupted. Is there an running build or a docker repo for this?
I think we should create a wiki page for this.

My docker repo for this: https://hub.docker.com/r/khaack/nliwod/

**Comment by KHaack** [comment]
otherwise a hint of the chatbot result structure for ```TEXT_WITH_URL``` and ```URL``` would be helpful. then I could also write tests.

**Comment by prasanthhs** [comment]
Structure of Response is under sask/chatbot/src/main/java/chatbot/io/response/. But i dont have any example data with me. I would also have to run hawk and collect it.

**Comment by RicardoUsbeck** [comment]
Change to TeBaQA (https://github.com/dice-group/TeBaQA)

Example http://185.2.103.92:8081/tebaqa/qa?query=How%20large%20is%20Germany?

**Comment by prasanthhs** [comment]
Supported calling tebaQA in chatbot as a temporary measure. Pull request #70.
