### ISSUE TITLE
eureka-server is not starting locally anymore

### ISSUE THREAD

**Issue by sajjadpz** [dice-group/sask#74]
After this latest changes, eureka-server is not starting anymore
```
hostname: @eureka.hostname@
```
and fails with following exception

```
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 4, column 15:
        hostname: @eureka.hostname@
```
How do we start the server, by the look of change, I see that the parameters will be passed externally, do we pass them now by `commandline` ?

**Comment by guru5590** [comment]
@sajjadpz , Please share the last git commit id post which you are experiencing this issue

**Comment by guru5590** [comment]
@sajjadpz, i just checked the master branch again, i'm able run eureka-server using **mvn clean spring-boot:run -P linux,local**

**Comment by sajjadpz** [comment]
@guru5590  - yes so in latest master branch , we will have to pass parameters also with `spring-boot:run` which were previously taken from `application.yml`
The documentation is not updated for these changes. Similar is the case with `web-client`

**Comment by KHaack** [comment]
https://desab.slack.com/messages/CBFBW735H/
